version: '3'

services:
  express:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - all
    environment:
      DATABASE_URL: "mongodb://mongo:27017/db"
      PORT: 3000
    command: npm start
  
  mongo:
    image: mongo:3
    container_name: mongo
    command: mongod --smallfiles --bind_ip_all
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - all

  mongo-express:
    image: "mongo-express:latest"
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - all
networks:
  all: